In [7]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv("input.csv", low_memory=False);

In [9]:
print("Total rows: {0}".format(len(data)))

Total rows: 3875

In [14]:
cols = list(data);
print(len(cols))

69

In [24]:
valcounts = {};
totcol = len(data);
for i in cols:
    valcounts[i] = totcol-data[i].count()

for key in valcounts:
    print(key+" "+str(valcounts[key])+"\n")

P. Name 0

P. Name Kepler 1547

P. Name KOI 2942

P. Zone Class 46

P. Mass Class 6

P. Composition Class 41

P. Atmosphere Class 85

P. Habitable Class 0

P. Min Mass (EU) 2727

P. Mass (EU) 33

P. Max Mass (EU) 3875

P. Radius (EU) 12

P. Density (EU) 41

P. Gravity (EU) 41

P. Esc Vel (EU) 41

P. SFlux Min (EU) 0

P. SFlux Mean (EU) 0

P. SFlux Max (EU) 0

P. Teq Min (K) 46

P. Teq Mean (K) 46

P. Teq Max (K) 46

P. Ts Min (K) 2126

P. Ts Mean (K) 2126

P. Ts Max (K) 2126

P. Surf Press (EU) 41

P. Mag 56

P. Appar Size (deg) 12

P. Period (days) 150

P. Sem Major Axis (AU) 35

P. Eccentricity 0

P. Mean Distance (AU) 35

P. Inclination (deg) 3151

P. Omega (deg) 0

S. Name 0

S. Name HD 3394

S. Name HIP 3354

S. Constellation 0

S. Type 84

S. Mass (SU) 47

S. Radius (SU) 112

S. Teff (K) 99

S. Luminosity (SU) 28

S. [Fe/H] 1738

S. Age (Gyrs) 1553

S. Appar Mag 929

S. Distance (pc) 1187

S. RA (hrs) 0

S. DEC (deg) 0

S. Mag from Planet 46

S. Size from Planet (deg) 128

S. No. Planets 0

S. No. Planets HZ 0

S. Hab Zone Min (AU) 115

S. Hab Zone Max (AU) 115

P. HZD 46

P. HZC 41

P. HZA 85

P. HZI 85

P. SPH 2074

P. Int ESI 0

P. Surf ESI 0

P. ESI 48

S. HabCat 0

P. Habitable 0

P. Hab Moon 0

P. Confirmed 0

P. Disc. Method 0

P. Disc. Year 0

Unnamed: 68 3873

In [28]:
perdic = {}
for key in valcounts:
    per = totcol - valcounts[key]
    per = per/totcol
    perdic[key] = 1-per;
for key in perdic:
    print(key+" "+str(perdic[key])+"\n")

P. Name 0.0

P. Name Kepler 0.3992258064516129

P. Name KOI 0.7592258064516129

P. Zone Class 0.011870967741935523

P. Mass Class 0.0015483870967741842

P. Composition Class 0.010580645161290314

P. Atmosphere Class 0.021935483870967776

P. Habitable Class 0.0

P. Min Mass (EU) 0.703741935483871

P. Mass (EU) 0.008516129032258068

P. Max Mass (EU) 1.0

P. Radius (EU) 0.0030967741935483684

P. Density (EU) 0.010580645161290314

P. Gravity (EU) 0.010580645161290314

P. Esc Vel (EU) 0.010580645161290314

P. SFlux Min (EU) 0.0

P. SFlux Mean (EU) 0.0

P. SFlux Max (EU) 0.0

P. Teq Min (K) 0.011870967741935523

P. Teq Mean (K) 0.011870967741935523

P. Teq Max (K) 0.011870967741935523

P. Ts Min (K) 0.5486451612903226

P. Ts Mean (K) 0.5486451612903226

P. Ts Max (K) 0.5486451612903226

P. Surf Press (EU) 0.010580645161290314

P. Mag 0.01445161290322583

P. Appar Size (deg) 0.0030967741935483684

P. Period (days) 0.03870967741935483

P. Sem Major Axis (AU) 0.00903225806451613

P. Eccentricity 0.0

P. Mean Distance (AU) 0.00903225806451613

P. Inclination (deg) 0.8131612903225807

P. Omega (deg) 0.0

S. Name 0.0

S. Name HD 0.8758709677419355

S. Name HIP 0.8655483870967742

S. Constellation 0.0

S. Type 0.02167741935483869

S. Mass (SU) 0.012129032258064498

S. Radius (SU) 0.02890322580645166

S. Teff (K) 0.025548387096774205

S. Luminosity (SU) 0.0072258064516128595

S. [Fe/H] 0.448516129032258

S. Age (Gyrs) 0.40077419354838706

S. Appar Mag 0.23974193548387102

S. Distance (pc) 0.30632258064516127

S. RA (hrs) 0.0

S. DEC (deg) 0.0

S. Mag from Planet 0.011870967741935523

S. Size from Planet (deg) 0.03303225806451615

S. No. Planets 0.0

S. No. Planets HZ 0.0

S. Hab Zone Min (AU) 0.029677419354838697

S. Hab Zone Max (AU) 0.029677419354838697

P. HZD 0.011870967741935523

P. HZC 0.010580645161290314

P. HZA 0.021935483870967776

P. HZI 0.021935483870967776

P. SPH 0.5352258064516129

P. Int ESI 0.0

P. Surf ESI 0.0

P. ESI 0.012387096774193584

S. HabCat 0.0

P. Habitable 0.0

P. Hab Moon 0.0

P. Confirmed 0.0

P. Disc. Method 0.0

P. Disc. Year 0.0

Unnamed: 68 0.9994838709677419

In [29]:
for key in perdic:
    if(perdic[key]>=0.5):
        data = data.drop(key, 1)
print(len(list(data)))

58

In [31]:
cols = list(data)
for i in cols:
    print(i + "\n")

P. Name

P. Name Kepler

P. Zone Class

P. Mass Class

P. Composition Class

P. Atmosphere Class

P. Habitable Class

P. Mass (EU)

P. Radius (EU)

P. Density (EU)

P. Gravity (EU)

P. Esc Vel (EU)

P. SFlux Min (EU)

P. SFlux Mean (EU)

P. SFlux Max (EU)

P. Teq Min (K)

P. Teq Mean (K)

P. Teq Max (K)

P. Surf Press (EU)

P. Mag

P. Appar Size (deg)

P. Period (days)

P. Sem Major Axis (AU)

P. Eccentricity

P. Mean Distance (AU)

P. Omega (deg)

S. Name

S. Constellation

S. Type

S. Mass (SU)

S. Radius (SU)

S. Teff (K)

S. Luminosity (SU)

S. [Fe/H]

S. Age (Gyrs)

S. Appar Mag

S. Distance (pc)

S. RA (hrs)

S. DEC (deg)

S. Mag from Planet

S. Size from Planet (deg)

S. No. Planets

S. No. Planets HZ

S. Hab Zone Min (AU)

S. Hab Zone Max (AU)

P. HZD

P. HZC

P. HZA

P. HZI

P. Int ESI

P. Surf ESI

P. ESI

S. HabCat

P. Habitable

P. Hab Moon

P. Confirmed

P. Disc. Method

P. Disc. Year

In [60]:
data.to_csv('input.csv');

In [62]:
types = {}

for i in data:
  
   types[i] = type(data[i][0]);

data["P. Mass (EU)"].fillna(data["P. Mass (EU)"].mean(), inplace=True)
data.to_csv('input.csv');

In [91]:
nonstrcols = list()


nan = float('nan');

for i in data:
    
    if(types[i] != str and pd.isnull(data[i][0])== False):
        data[i].fillna(data[i].mean(), inplace=True)
        nonstrcols.append(i);
        
    if(types[i] == str):
        valco = data[i].value_counts().to_dict();
        valco2 = data[i].value_counts();
        print(max(valco2))
        maxval = max(valco, key=valco.get);
        data[i].fillna(maxval, inplace=True)
    print(data[i].isnull().sum())

False
1
0
1547
3297
0
1279
0
2115
0
2457
0
3820
0
0
0
0
0
0
46
0
46
0
46
0
0
0
0
0
0
0
150
0
0
0
0
8
0
1368
0
1307
0
0
0
0
0
1738
0
929
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1490
0
1577
0

In [92]:
data.to_csv('input.csv');